- hosts: multi
  remote_user: root
  become: true
  roles:
    - common

- hosts: control_plane
  remote_user: root
  become: true
  roles:
    - control

- hosts: worker_nodes
  remote_user: root
  become: true
  roles:
    - worker
