- name: "Copy hosts file"
  ansible.builtin.template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

- name: "Join control plane"
  ansible.builtin.shell: "kubeadm join --token {{ kubeadm_token }} control:6443 --discovery-token-ca-cert-hash sha256:{{ kubeadm_discovery_token }} | tee kubeadm-join.out"
  # args:
  #   chdir: /root/k8s
  #   creates: kubeadm-init.out
  